[project]
name = "biobeamer-launcher"
version = "0.1.0"
description = "Launcher for BioBeamer with config fetching and version management."
authors = ["Your Name <your.email@example.com>"]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["biobeamer_launcher"]
package-dir = {"" = "src"}
